Algoritmo "semnome"
Var n1, soma, subt, multi, divi: real
n2 : inteiro
Inicio
Escreva ("Digite o primeiro número ")
Leia (n1)
Escreva ("Digite o segundo número ")
Leia (n2)
Enquanto (n2<=0) faca
Escreva("Digite um número positivo e diferente de zero: ")
Leia (n2)
fimenquanto
soma:= n1+n2
subt:= n1-n2
multi:= n1*n2
divi:= n1/n2
Escreva ("A Soma é: ", soma)
Escreva (" A Subtração é: ", subt)
Escreva (" A Multipicação é: ", multi)
Escreva (" A Divisão é: ", divi)
Fimalgoritmo